### ISSUE TITLE
Guide / Essentials

### ISSUE THREAD

**Issue by edimitchel** [edimitchel/docs-fr#9]
- [x] Create application #5  @edimitchel 
- [ ] Template Syntax #117 @edimitchel
- [ ] Reactivity Fundamentals
- [ ] Computed Properties
- [ ] Class and Style Bindings
- [x] Conditional Rendering #116 @Rachiid007
- [ ] List Rendering
- [ ] Event Handling
- [ ] Form Input Bindings
- [ ] Lifecycle Hooks
- [ ] Watchers
- [ ] Template Refs
- [ ] Components Basics

**Comment by Wilfried71** [comment]
Hello,

I can help on the french translations, but it's the first time I work on an open source project so I'm a little bit confused. 
What am I supposed to do ?

**Comment by edimitchel** [comment]
> Hello,
> 
> I can help on the french translations, but it's the first time I work on an open source project so I'm a little bit confused. 
> What am I supposed to do ?

Hi!
First join us on discord https://discord.gg/tkWq5gFE.
We'll schedule a virtual meetup to explain how to contribute to the project.
Also, this project would probably move into the @vuejs-translations org in nowadays
